"""delete column release_date_uk

Revision ID: 01ae6765b98d
Revises: 9392d2b54572
Create Date: 2020-08-06 17:27:10.361857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ae6765b98d'
down_revision = '9392d2b54572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('movie', 'release_date_uk')
    # ### end Alembic commands ###
    with op.batch_alter_table('movie') as batch_op:
        batch_op.drop_column('release_date')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_date_uk', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
