"""movie fields

Revision ID: 0622315135a3
Revises: 3dcbe19a2e8d
Create Date: 2020-04-28 21:45:17.500257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0622315135a3'
down_revision = '3dcbe19a2e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('movie', sa.Column('certificate', sa.String(length=16), nullable=True))
    op.add_column('movie', sa.Column('director', sa.String(length=64), nullable=True))
    op.add_column('movie', sa.Column('plot_summary', sa.String(length=512), nullable=True))
    op.add_column('movie', sa.Column('poster_url', sa.String(length=256), nullable=True))
    op.add_column('movie', sa.Column('rating_count', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('rating_value', sa.Float(), nullable=True))
    op.add_column('movie', sa.Column('release_date', sa.String(length=128), nullable=True))
    op.add_column('movie', sa.Column('runtime', sa.String(length=16), nullable=True))
    op.add_column('movie', sa.Column('url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'url')
    op.drop_column('movie', 'runtime')
    op.drop_column('movie', 'release_date')
    op.drop_column('movie', 'rating_value')
    op.drop_column('movie', 'rating_count')
    op.drop_column('movie', 'poster_url')
    op.drop_column('movie', 'plot_summary')
    op.drop_column('movie', 'director')
    op.drop_column('movie', 'certificate')
    op.drop_column('movie', 'category')
    # ### end Alembic commands ###
