"""character order field

Revision ID: 29905aa2e122
Revises: 14b840151c2f
Create Date: 2020-06-17 08:46:56.335379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29905aa2e122'
down_revision = '14b840151c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'order')
    # ### end Alembic commands ###
