"""update character model

Revision ID: 2f2f0229ae34
Revises: 29905aa2e122
Create Date: 2020-07-31 09:01:20.576939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2f0229ae34'
down_revision = '29905aa2e122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('character', 'movie_year')
    # op.drop_column('character', 'movie_title')
    # op.drop_column('character', 'actor_name')
    # ### end Alembic commands ###
    with op.batch_alter_table('character') as batch_op:
        batch_op.drop_column('movie_year')
        batch_op.drop_column('movie_title')
        batch_op.drop_column('actor_name')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('actor_name', sa.VARCHAR(length=128), nullable=True))
    op.add_column('character', sa.Column('movie_title', sa.VARCHAR(length=128), nullable=True))
    op.add_column('character', sa.Column('movie_year', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
