"""director relationship 2

Revision ID: 39ddd09677b5
Revises: ee3d21c41acc
Create Date: 2020-08-07 16:39:51.722284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ddd09677b5'
down_revision = 'ee3d21c41acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'people', ['director_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('director_id')

    # ### end Alembic commands ###
