"""new fields in user model

Revision ID: 440cd4bf9582
Revises: c121bc183751
Create Date: 2020-04-23 17:58:36.307471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440cd4bf9582'
down_revision = 'c121bc183751'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
