"""delete column director

Revision ID: 52521046886e
Revises: 83ef35a68810
Create Date: 2020-08-06 17:47:41.285742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52521046886e'
down_revision = '83ef35a68810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('movie', 'director')
    # ### end Alembic commands ###
    with op.batch_alter_table('movie') as batch_op:
        batch_op.drop_column('director')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('director', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
