"""movie field stars

Revision ID: 5ea986903b37
Revises: 2bd98972d851
Create Date: 2020-04-23 22:15:13.989128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea986903b37'
down_revision = '2bd98972d851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('stars', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'stars')
    # ### end Alembic commands ###
