"""people table index

Revision ID: 5f1654c61a38
Revises: e595639eaef2
Create Date: 2020-06-09 21:43:34.286766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1654c61a38'
down_revision = 'e595639eaef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_name'), table_name='people')
    # ### end Alembic commands ###
