"""delete column release_date

Revision ID: 7dde762b575a
Revises: 07035cab9a29
Create Date: 2020-08-06 17:23:12.681021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dde762b575a'
down_revision = '07035cab9a29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('movie', 'release_date')
    # ### end Alembic commands ###
    with op.batch_alter_table('movie') as batch_op:
        batch_op.drop_column('release_date')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('release_date', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
