"""new column director_name

Revision ID: 83ef35a68810
Revises: 15253f648026
Create Date: 2020-08-06 17:45:01.602009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83ef35a68810'
down_revision = '15253f648026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('director_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'director_name')
    # ### end Alembic commands ###
