"""delete runtime field

Revision ID: 9efd67749c8b
Revises: 0622315135a3
Create Date: 2020-04-29 21:32:44.886879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9efd67749c8b'
down_revision = '0622315135a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie') as batch_op:
        batch_op.drop_column('runtime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('runtime', sa.VARCHAR(length=16), nullable=True))
    # ### end Alembic commands ###
