"""empty message

Revision ID: ace3c4c93c8b
Revises: 761c4d4fc797
Create Date: 2020-08-06 09:44:01.211884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace3c4c93c8b'
down_revision = '761c4d4fc797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_foreign_key(None, 'movie', 'people', ['director_id'], ['id'])
    # ### end Alembic commands ###
    with op.batch_alter_table('movie') as batch_op:
        batch_op.add_column(sa.Column('director_id', sa.Integer, nullable=True))
        batch_op.create_foreign_key('director_id', 'people', ['director_id'], ['id'])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    # ### end Alembic commands ###
