"""director relationship 3

Revision ID: d20a5729b6c7
Revises: 39ddd09677b5
Create Date: 2020-08-07 17:03:22.351083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20a5729b6c7'
down_revision = '39ddd09677b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_movie_director_id_people'), 'people', ['director_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movie_director_id_people'), type_='foreignkey')
        batch_op.drop_column('director_id')

    # ### end Alembic commands ###
