"""people table

Revision ID: e595639eaef2
Revises: b2955ad9e338
Create Date: 2020-06-09 21:42:12.906890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e595639eaef2'
down_revision = 'b2955ad9e338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_id', sa.Integer(), nullable=True),
    sa.Column('modified_timestamp', sa.DateTime(), nullable=True),
    sa.Column('modified_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=64), nullable=True),
    sa.Column('image_url', sa.String(length=256), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('birthname', sa.String(length=128), nullable=True),
    sa.Column('height', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['created_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_created_timestamp'), 'people', ['created_timestamp'], unique=False)
    op.create_index(op.f('ix_people_modified_timestamp'), 'people', ['modified_timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_people_modified_timestamp'), table_name='people')
    op.drop_index(op.f('ix_people_created_timestamp'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
