"""remove director relationship

Revision ID: ee3d21c41acc
Revises: 6b145579bb8b
Create Date: 2020-08-07 16:16:04.909956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3d21c41acc'
down_revision = '6b145579bb8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.drop_column('director_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_id', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
